/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./App.tsx", "./src/**/*.{ts,tsx}"],
  presets: [require("nativewind/preset")],
  darkMode: "class",
  // NativeWind has no CSS-custom-property swap like web's `:root[data-theme]` (index.css),
  // so each token gets an explicit "-dark" twin instead; every screen pairs them as
  // `bg-surface dark:bg-surface-dark`. Same hex values as web/src/index.css — keep in sync.
  theme: {
    extend: {
      colors: {
        bg: "#eef2f0",
        "bg-dark": "#0a0f0d",
        "stage-bg": "#e3e9e5",
        "stage-bg-dark": "#060a09",
        surface: "#ffffff",
        "surface-dark": "#121a17",
        "surface-2": "#f1f5f2",
        "surface-2-dark": "#1b2521",
        "surface-3": "#e5ebe6",
        "surface-3-dark": "#233029",
        border: "#d7ded9",
        "border-dark": "#2a3733",
        "border-soft": "#e2e8e4",
        "border-soft-dark": "#1e2925",
        text: "#0f1713",
        "text-dark": "#eaf2ed",
        "text-dim": "#54625c",
        "text-dim-dark": "#8fa79c",
        "text-faint": "#8a978f",
        "text-faint-dark": "#5e7268",
        accent: "#0f9a82",
        "accent-dark": "#2fe6c6",
        "accent-dim": "#0c7d69",
        "accent-dim-dark": "#1ca98f",
        "accent-ink": "#ffffff",
        "accent-ink-dark": "#04211c",
        gold: "#a5701a",
        "gold-dark": "#e8b34d",
        win: "#1f9d4a",
        "win-dark": "#5bc26b",
        draw: "#b9760a",
        "draw-dark": "#d9a441",
        loss: "#c23b2e",
        "loss-dark": "#e2584b",
      },
    },
  },
  plugins: [],
};
