CREATE TABLE users (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at   TIMESTAMP NOT NULL,
    updated_at   TIMESTAMP NOT NULL,
    display_name VARCHAR(120) NOT NULL,
    email        VARCHAR(255) UNIQUE,
    phone        VARCHAR(32) UNIQUE,
    google_id    VARCHAR(255) UNIQUE,
    role         VARCHAR(20) NOT NULL DEFAULT 'USER',
    active       BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT chk_users_role CHECK (role IN ('USER', 'ADMIN'))
);

CREATE TABLE refresh_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMP NOT NULL,
    updated_at  TIMESTAMP NOT NULL,
    user_id     BIGINT NOT NULL REFERENCES users (id),
    token_hash  VARCHAR(255) NOT NULL UNIQUE,
    expires_at  TIMESTAMP NOT NULL,
    revoked     BOOLEAN NOT NULL DEFAULT FALSE,
    revoked_at  TIMESTAMP,
    device_info VARCHAR(255)
);
CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens (user_id);

CREATE TABLE otp_codes (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at   TIMESTAMP NOT NULL,
    updated_at   TIMESTAMP NOT NULL,
    destination  VARCHAR(255) NOT NULL,
    channel      VARCHAR(10) NOT NULL,
    code_hash    VARCHAR(255) NOT NULL,
    expires_at   TIMESTAMP NOT NULL,
    consumed_at  TIMESTAMP,
    attempts     INT NOT NULL DEFAULT 0,
    CONSTRAINT chk_otp_codes_channel CHECK (channel IN ('EMAIL', 'SMS'))
);
CREATE INDEX idx_otp_codes_destination_channel ON otp_codes (destination, channel);

CREATE TABLE teams (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMP NOT NULL,
    updated_at  TIMESTAMP NOT NULL,
    name        VARCHAR(120) NOT NULL,
    code        VARCHAR(5) NOT NULL,
    crest_url   VARCHAR(500),
    color_hex   VARCHAR(7),
    star_level  INT NOT NULL,
    league_type VARCHAR(120) NOT NULL,
    created_by  BIGINT REFERENCES users (id),
    active      BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT chk_teams_star_level CHECK (star_level BETWEEN 2 AND 5)
);
CREATE INDEX idx_teams_league_type ON teams (league_type);

CREATE TABLE leagues (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    name       VARCHAR(120) NOT NULL,
    owner_id   BIGINT NOT NULL REFERENCES users (id)
);
CREATE INDEX idx_leagues_owner_id ON leagues (owner_id);

CREATE TABLE players (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at   TIMESTAMP NOT NULL,
    updated_at   TIMESTAMP NOT NULL,
    league_id    BIGINT NOT NULL REFERENCES leagues (id),
    display_name VARCHAR(120) NOT NULL,
    user_id      BIGINT REFERENCES users (id),
    CONSTRAINT uq_players_league_display_name UNIQUE (league_id, display_name)
);
CREATE INDEX idx_players_league_id ON players (league_id);

CREATE TABLE matches (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at   TIMESTAMP NOT NULL,
    updated_at   TIMESTAMP NOT NULL,
    league_id    BIGINT NOT NULL REFERENCES leagues (id),
    player1_id   BIGINT NOT NULL REFERENCES players (id),
    player2_id   BIGINT NOT NULL REFERENCES players (id),
    team1_id     BIGINT NOT NULL REFERENCES teams (id),
    team2_id     BIGINT NOT NULL REFERENCES teams (id),
    score1       INT NOT NULL,
    score2       INT NOT NULL,
    recorded_at  TIMESTAMP NOT NULL,
    recorded_by  BIGINT REFERENCES users (id),
    CONSTRAINT chk_matches_score1 CHECK (score1 >= 0),
    CONSTRAINT chk_matches_score2 CHECK (score2 >= 0)
);
CREATE INDEX idx_matches_league_id ON matches (league_id);
