CREATE TABLE league_types (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    name       VARCHAR(120) NOT NULL UNIQUE
);

-- Backfill one league_type row per distinct value already used by teams (no-op on an empty table).
INSERT INTO league_types (created_at, updated_at, name)
SELECT DISTINCT CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, league_type FROM teams;

ALTER TABLE teams ADD COLUMN league_type_id BIGINT;

UPDATE teams t
SET league_type_id = (SELECT lt.id FROM league_types lt WHERE lt.name = t.league_type);

ALTER TABLE teams ALTER COLUMN league_type_id SET NOT NULL;
ALTER TABLE teams ADD CONSTRAINT fk_teams_league_type FOREIGN KEY (league_type_id) REFERENCES league_types (id);

DROP INDEX idx_teams_league_type;
ALTER TABLE teams DROP COLUMN league_type;

CREATE INDEX idx_teams_league_type_id ON teams (league_type_id);
