-- "Reset league" used to delete every match; it now closes the current season and opens a
-- new one instead, so past scores/standings survive under a "Geçmiş Ligler" (past leagues)
-- view instead of being destroyed. ended_at IS NULL marks a league's one active season.
CREATE TABLE seasons (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    league_id  BIGINT NOT NULL REFERENCES leagues (id),
    name       VARCHAR(120) NOT NULL,
    started_at TIMESTAMP NOT NULL,
    ended_at   TIMESTAMP
);
CREATE INDEX idx_seasons_league_id ON seasons (league_id);

ALTER TABLE matches ADD COLUMN season_id BIGINT REFERENCES seasons (id);

-- Backfill: every existing league gets one active ("Sezon 1") season, and every match it
-- already has (recorded before seasons existed) is attached to that season — nothing is lost.
INSERT INTO seasons (created_at, updated_at, league_id, name, started_at, ended_at)
SELECT now(), now(), id, 'Sezon 1', created_at, NULL FROM leagues;

UPDATE matches m
SET season_id = (SELECT s.id FROM seasons s WHERE s.league_id = m.league_id AND s.ended_at IS NULL);

ALTER TABLE matches ALTER COLUMN season_id SET NOT NULL;
CREATE INDEX idx_matches_season_id ON matches (season_id);
